oidc:
    issuer: ${OIDC_ISSUER:http://localhost:8080/realms/dev}

api:
    url: ${API_URL:http://localhost:3000}

rulesets:
    - name: gapi
      url: https://${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD}@artifactory.devops.telekom.de/artifactory/published-api-linting-rules/spectral/v2/latest/gapi-linter-rules.spectral.yaml
      refreshInterval: 300
    - name: basic
      url: https://${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD}@artifactory.devops.telekom.de/artifactory/published-api-linting-rules/spectral/v2/latest/basis-linter-rules.spectral.yaml
      refreshInterval: 300

schemas:
    - name: openapi:2.0
      url: file://public/schemas/openapi/2.0/schema.json
    - name: openapi:2.0-remote
      url: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v2.0/schema.json
    - name: openapi:3.0
      url: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json
    - name: openapi:3.1
      url: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json

ui:
    enabled: true
    url: ${EDITOR_URL:http://localhost:5173}
    apiBase: ''
