services:
  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=secret
    networks:
      - mynetwork

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
    networks:
      - mynetwork

  app:
    build: 
      context: .
      dockerfile: build/Dockerfile.all-in-one
    ports:
      - 3000:3000
    environment:
      - ARTIFACTORY_USER=${ARTIFACTORY_USER}
      - ARTIFACTORY_PASSWORD=${ARTIFACTORY_PASSWORD}
    depends_on:
      - keycloak
      - jaeger
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
